app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "app"
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path("search/", views.PostSearch, name="search"),
    path("create/", views.PostCreate, name="create"),
    path("<int:post_id>/", views.PostDetail, name="detail"),
    path("update/<int:post_id>/", views.PostUpdate, name="update"),
    path("delete/<int:post_id>/", views.PostDelete, name="delete"),
    path("<int:post_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
]

epii/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("", include("staticpages.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Alemanha Universitária</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Bootstrap cdn -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/journal/bootstrap.min.css"> -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/journal/bootstrap.min.css">

        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css"> -->
    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="mainNav">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Alemanha Universitária</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                  <a class="nav-link text-black font-weight-bold" href="{% url 'app:index' %}">Postagens</a>
                </li>
                <li class="nav-item text-black">
                  <a class="nav-link text-black font-weight-bold" href="{% url 'app:lists' %}">Favoritos da Comunidade</a>
                </li>
                <li class="nav-item text-black">
                  <a class="nav-link text-black font-weight-bold" href="{% url 'about' %}">Sobre</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <nav id="navegacao-principal">
          <ul style="list-style-type: none; padding: 0;">
              {% if user.is_authenticated %}
                  <li style="display: inline-block;">Logado com {{ user.username }}</li>
                  <li style="display: inline-block; margin-left: 10px;"><a href="{% url 'logout' %}" class="btn btn-danger">Log out</a></li>
              {% else %}
                  <li style="display: inline-block;"><a href="{% url 'login' %}" class="btn btn-danger">Log in</a></li>
              {% endif %}
              {% if not user.is_authenticated %}
                  <li style="display: inline-block;"><a href="{% url 'signup' %}" class="btn btn-danger">Signup</a></li>
              {% endif %}
              <li style="display: inline-block;"><a href="{% url 'app:index' %}" class="btn btn-danger">Posts</a></li>
              <li style="display: inline-block;"><a href="{% url 'app:lists' %}" class="btn btn-danger">Listas</a></li>
              <li style="display: inline-block;"><a href="{% url 'app:create' %}" class="btn btn-primary">Faça uma postagem!</a></li>
              <li style="display: inline-block;"><a href="{% url 'app:categories' %}" class="btn btn-danger">Categorias</a></li>
          </ul>
      </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
          <p class="m-0 text-dark text-center ">Copyright &copy; 2023 AleUni </p>
        </footer>
    </body>
      
</html>