app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "app"
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path("search/", views.PostSearch, name="search"),
    path("create/", views.PostCreate, name="create"),
    path("<int:post_id>/", views.PostDetail, name="detail"),
    path("update/<int:post_id>/", views.PostUpdate, name="update"),
    path("delete/<int:post_id>/", views.PostDelete, name="delete"),
    path("<int:post_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
]

epii/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("", include("staticpages.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

app/models.py
from django.db import models
from django.conf import settings

# Create your models here.



class Post(models.Model):
    name = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    image_url = models.URLField(max_length=200, null=True)
    texto = models.CharField(max_length=3000, null=True)
    data = models.DateField(auto_now_add=True)
    def __str__(self):
        return f"{self.name}"


class Comentario(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    data = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f"{self.name} by {self.author}"

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post, blank = True)

    def __str__(self):
        return f'{self.name}'

app/templates/app/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
    <h2>Sobre este site</h2>
    <p>Los geht's!</p>
    <p>Com grande satisfação, permita-me apresentar-me como Gabriel Dias, estudante de graduação em Engenharia Mecatrônica na renomada Escola Politécnica da Universidade de São Paulo (USP). É com entusiasmo e um profundo compromisso com o compartilhamento de conhecimento que criei este website.

        O motivo que me levou a estabelecer esta plataforma é a minha recente seleção pela instituição para participar de um programa de Duplo Diploma na cidade de Darmstadt, na Alemanha. Esta oportunidade única de aprimorar meu conhecimento e expandir meus horizontes acadêmicos em um cenário internacional inspirou-me a criar um espaço que possa servir como uma fonte valiosa de informações e orientações para outros estudantes que se encontrem em circunstâncias semelhantes.
        
        A Alemanha, um país conhecido por sua excelência acadêmica, rica herança cultural e avanços tecnológicos, será o palco de nossa jornada acadêmica. No entanto, reconheço que enfrentar um novo sistema educacional e adaptar-se a uma nova cultura pode ser desafiador. Portanto, através deste website, almejo fornecer um guia abrangente que não apenas aborde o processo de candidatura e admissão, mas também ofereça insights sobre a vida na Alemanha, dicas práticas de integração e sugestões para uma experiência acadêmica enriquecedora.
        
        À medida que esta plataforma evolui, pretendo compartilhar informações atualizadas sobre os procedimentos burocráticos, requisitos de proficiência em idioma, opções de acomodação, atividades culturais imperdíveis na Alemanha e estratégias para o sucesso acadêmico. Além disso, estou ansioso para apresentar relatos pessoais de minhas próprias experiências no exterior e insights que possam ajudar a comunidade de estudantes de intercâmbio.
        
        Acredito firmemente que a educação transcende fronteiras e que a aprendizagem não se limita apenas às salas de aula, mas também à imersão em novos ambientes e à absorção de diferentes perspectivas. Assim, convido todos os interessados nesta emocionante jornada a acompanharem este site em sua evolução e a contribuírem com suas próprias experiências e conhecimentos.
        
        Nossa missão é construir uma comunidade de estudantes de intercâmbio dedicados a facilitar a transição para estudar no exterior, criando uma rede de apoio e compartilhando informações valiosas. Espero que este website seja uma fonte de inspiração e orientação para aqueles que embarcarão nesta incrível aventura acadêmica em Darmstadt e além.
        
        Fico à disposição para qualquer dúvida ou sugestão que possam surgir ao longo deste percurso emocionante. Juntos, podemos tornar esta jornada educacional no exterior ainda mais gratificante e enriquecedora.
        
        Atenciosamente,
        
        Gabriel Dias</p>
{% endblock content %}

app/templates/app/categories.html
{% extends 'base.html' %}
{% block title %}
Categorias 
{% endblock title %}
{% block content %}
<div class="col-md-4 float-center ">
    <div class="card my-4">
      <h5 class="card-header">Categorias</h5>
      <div class="card-body">
        <h2>Todas as Categorias</h2>
            {% if category_list %}
            <section >
                {% for category in category_list %}
                <article >
                    <a href="{% url 'app:category' category.id %}" > <p> {{ category.name}}</p></a>
                </article>
                {% endfor %}
            </section>
            {% else %}
            <p>Não foi encontrado nenhuma categoria.</p>
            {% endif %}
      </div>
    </div>
  </div>


{% endblock content %}

app/templates/app/category.html
{% extends 'base.html' %}
{% block title %}
Categoria {{category.name}}
{% endblock title %}
{% block content %}


<h2>Todos os posts da Categoria {{category.name}} </h2>
<p>{{category.description}}</p>
{% if category %}
<section >
    {% for post in category.posts.all %}
    <article >
        <a href="{% url 'app:detail' post.id %}" > <p> {{ post.name}}</p></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post relacionada à categoria {{category.name}}.</p>
{% endif %}

{% endblock content %}

app/templates/app/comentario.html
{% extends 'base.html' %}
{% block content %}
    <h2>Comentar post {{ post.name }} ({{ post.categoria }})</h2>
    <form action="{% url 'app:comentario' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postar Comentário</button>
    </form>
    <p>
        <a href="{% url 'app:detail' post.id %}">Voltar para a página do post</a>
    </p>
{% endblock content %}

app/templates/app/creat_list.html
{% extends 'base.html' %}
{% block title %}
    Criar postagem
{% endblock title %}
{% block content %}
    <h2>Criar lista de posts favoritos</h2>
    <form action="{% url 'app:create-list' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

app/templates/app/create.html
{% extends 'base.html' %}
{% block title %}
    Criar postagem
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-3 left">
        <div class="card mb-4">
          <div class="card-body">
            <h2>Adicionar post</h2>
            <form action="{% url 'app:create' %}" method="post">
                {% csrf_token %}
                {{ post_form.as_p }}
                <button type="submit">Criar</button>
            </form> 
          </div>
        </div>
      </div>
    </div>
  </div>
    
{% endblock content %}

app/templates/app/delete.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'app:delete' post.id %}" method="post">
        {% csrf_token %}
        <p>Você tem certeza que deseja apagar o post"{{ post.name }} ({{ investment.categoria }})"?</p>
        <button type="submit">Apagar</button>
    </form>
{% endblock content %}

app/templates/app/detail.html
{% extends 'base.html' %}
{% block title %}
    <strong>{{ post.name }}</strong> (<strong>{{ post.categoria }}</strong>)
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-3 left">
        <div class="card mb-4">
          <div class="card-body">
            <h2>{{ post.name }}</h2>
                <section class="dados-de-post">
                    <img src="{{ post.image_url }}" alt="Foto do artigo {{ post.name }}" width="300">
                    <ul>
                        <li style="display: block;"><u>Nome</u>: <strong>{{ post.name }}</strong></li>
                        <li style="display: block;"><u>Categoria</u>: <strong>{{ post.categoria }}</strong></li>
                        <li style="display: block;"><u>Data</u>: <strong>{{post.data}}</strong></li>
                        <li style="display: block;"><u>Texto</u>: {{ post.texto }}</li>
                        {% if post.list_set.all %}<li><u>Incluso nas listas</u>: {{ post.list_set.all|join:", " }}</li>{% endif %}
                        <li style="display: inline-block;"></li>>
                            <a href="{% url 'app:update' post.id %}" class="btn btn-primary">Editar</a>
                        </li>
                        <li style="display: inline-block;"></li>>
                            <a href="{% url 'app:delete' post.id %}" class="btn btn-primary">Apagar</a>
                        </li>
                    </ul>
                </section>
          </div>
        </div>
      </div>
    </div>
  </div>
    
    <hr>
    <section>
        <header>
            <h3>Comentários</h3>
        </header>
        <ul>
            {% if post.comentario_set.all %}
                {% for comentario in post.comentario_set.all|dictsortreversed:"id" %}
                    <figure>
                        <blockquote>
                            "{{ comentario.text }}"
                        </blockquote>
                        <figcaption>—{{ comentario.author }}, {{comentario.data}}</figcaption>
                    </figure>
                {% endfor %}
            {% else %}
                <p>Ainda não existe nenhum comentário para este Post.</p>
            {% endif %}
        </ul>
        <hr>
        <a href="{% url 'app:comentario' post.pk %}">
            <button>Crie seu Comentário</button>
        </a>
</section>
{% endblock content %}

app/templates/app/index.html
{% extends "base.html" %}
{% block content %}
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class=" site-heading my-4 mt-3 text-black"> Está página é para você que pretende fazer ou já esta fazendo Duplo Diploma na Alemanha! </h3>
          <p class="text-dark">Los geht's! </p>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ post.name }}</h2>
          <p class="card-text text-muted h6">{{ post.categoria }} | {{ post.data}} </p>
          <p class="card-text">{{post.texto|slice:":200"}}</p>
          <a href="{% url 'app:detail' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% block sidebar %} 
    {% include 'app/sidebar.html' %} 
    {% endblock sidebar %}
  </div>
</div>
{%endblock%}

app/templates/app/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Favoritos da Comunidade</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for post in list.app.all%}
            {% for post in list.app.all|dictsortreversed:"id" %}
            <div class="card">
                <a href="{% url 'app:detail' post.id %}"><img src="{{ post.image_url }}"
                        alt="Foto do Artigo {{ post.name}}"></a>
                <p>{{ post.name }} ({{ post.categoria }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'app:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

app/templates/app/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de posts por Nome</h2>
<form action="{% url 'app:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.image_url }}" alt="Foto do artigo {{ post.name}}">
        <p>{{ post.name }} ({{ post.categoria }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

app/templates/app/sidebar.html
{% block sidebar %}

<style>
  .card {
    box-shadow: 0 16px 48px #6a6a6b;
  }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
  <div class="card my-4">
    <h5 class="card-header">About</h5>
    <div class="card-body">
      <p class="card-text"> Me Chamo Gabriel Dias e desenvolvi esta página no intuito de auxiliar aqueles que pretendem fazer Duplo Diploma com a Escola Politécnica da USP. </p>
      <a href="https://pmr3304-12624565.e.usp.br/ep" class="btn btn-danger">Para saber mais!</a>
      <a href="https://docs.djangoproject.com/en/3.1/" class="btn btn-secondary">Caso queira ver o repositório!</a>
    </div>
  </div>
</div>

{% endblock sidebar %}

app/templates/app/update.html
{% extends 'base.html' %}
{% block content %}
    <h2>Atualizar Dados do post {{ post.name }}</h2>
    <form method="POST" action="{% url 'app:update' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
{% endblock content %}